### ISSUE TITLE
cytoband shift for `pergola_rules`

### ISSUE THREAD

**Issue by ionase** [cbcrg/pergola#22]
It would be cool to have the option to put a starting time for the light/dark phases as encoded by the cytoband file in the `pergola_rules.py` script.

**Comment by JoseEspinosa** [comment]
This issue needs the implementation of two options in `pergola` main script:
* `starting_phase` which should be the first phase to appear in the cytoband file and the phases bed file
* `shift` time shift for the first phase, it means that the first phase will be set to finish with this time shift and from there all the other phases will be set using `delta` option of `mapping.write_cytoband()`, by default 43200 seconds (12 hours).
