### ISSUE TITLE
Allow ordinal selection of the columns of a headless CSV input file for the mapping

### ISSUE THREAD

**Issue by JoseEspinosa** [cbcrg/pergola#3]
When the CSV input file has not header, the corresponding mappings to the Pergola ontology can only be mapped by naming the columns using `--fields_read, -s ` option. It would more intuitive to allow also to use the order of the columns.

**Comment by JoseEspinosa** [comment]
Just create a default option that when headers are not provided by default the colums are set to numeric values in the order inside the file. This way the mapping becomes:
`behavioral_file:1 > pergola:start`

**Comment by cnotred** [comment]
Hi José

How are things with the ms?

Cedric 

###################################
Dr Cedric Notredame
Group Leader
Notredame's lab - Comparative Bioinformatics Group
Bioinformatics and Genomics Programme
Room 440.03

Centre de Regulació Genòmica (CRG)
Dr. Aiguader, 88
08003 Barcelona
Spain

Ph#     + 34 93 316 02 71
Fax#    + 34 93 316 00 99
Mobile# + 34 66 250 47 82

email   cedric.notredame@crg.eu
url     www.tcoffee.org
blog    cedricnotredame.blogspot.com
ORC-ID: 0000-0003-1461-0988
###################################
